### ISSUE TITLE
Shot direction doesn't reflect the shooter's mind

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/Ball#13]
This topic is related to #9 

I made a video for simple explanation. [Please take a look](https://youtu.be/PJQVD72ut0o)
Can you explain me why the shot was not on target(the goal)?
In this video I was clearly aiming the goal

**Comment by LazoYoung** [comment]
![default](https://user-images.githubusercontent.com/9482578/43525917-f387b4a4-95dd-11e8-810b-46cdc022630a.png)

**Comment by Shynixn** [comment]
As this issue isn't that trivial I haven't dealed with it yet. The problem is that the direction of the player is completely ignored at the moment. 

![2](https://user-images.githubusercontent.com/11297593/43529112-d623d5ec-95aa-11e8-81e7-1236eb5013b2.JPG)

Translated to your video:

![2](https://user-images.githubusercontent.com/11297593/43529122-ddcfa0c8-95aa-11e8-9360-da6517a3afff.JPG)

**Comment by Shynixn** [comment]
It takes the location between the ball and the player, calculates the vector between them, normalizes it and applies the horizontal and vertical modifier values.

**Comment by LazoYoung** [comment]
Aha! So your plugin never counts the player's facing direction, am I correct?
Then we must have to deal with it one day.
I'd like to help you out refactoring the shot logic if you allow me

**Comment by LazoYoung** [comment]
I'm thinking the new design for ball physic. [Checkout this video](https://youtu.be/8I3QyaQLnM4)

Let me explain my idea: 
1. Keep the current vector calculation (vector between player and ball) as it is.
2. When a shot occurs, initial shot vector will be calculated and applied to the ball's velocity.
3. Calculate the angle between the player's direction and the shot vector. Let's call it θ
4. If θ is bigger than a certain threshold, calculate the extra force vector.
5. The extra vector is a subtraction of two vectors: (player's direction - initial shot vector)
6. Normalize the extra vector and apply to the ball
7. Increase the extra vector every second/tick

This is the result I'm expecting:
![expectation](https://imgur.com/TrfxirD)

**Comment by Shynixn** [comment]
* I have changed the maven pom.xml so the lib folder with all spigot libaries is now obsolete for Ball, BlockBall (soon PetBlocks and the other repositories). Instead you need to install the spigot libaries only once into your local maven repository. After executing maven refresh all dependencies should be fetched.
* You can find the current (redundant) kick logic in the CustomDesign.java file at the kickByEntity method.
*  Set the output path of the Ball.jar test plugin in the ball-bukkit-plugin folder. 
" <outputFile>D:/Temp/plugins/Ball.jar</outputFile>"
* Start/Restart/Reload your server once the Ball.jar is built and you can spawn a ball by typing /ball.
         





https://github.com/Shynixn/Ball/blob/master/ball-bukkit-core/src/main/java/com/github/shynixn/ball/bukkit/core/nms/v1_12_R1/CustomDesign.java

**Comment by LazoYoung** [comment]
Okay thanks! I'll try to make spare time to make it.
But I'm not sure if I can finish it until this year because right now I'm studying for the major exam

**Comment by Shynixn** [comment]
That's fine. :)

**Comment by LazoYoung** [comment]
Curve feature is confirmed to be working so I'll close the issue.
